### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by CiDi-IT**
Translation BESST Parameter 6011-6012

### CODE REVIEW

**Comment by Ornias1993** [comment]
Could you just make this into a nicely structured table in an MD file?
Including the bit number for each parameter, as it's listed in BESST.

**Review by Ornias1993 — CHANGES_REQUESTED** [review]
see comment

**Review by CiDi-IT — COMMENTED** [review]
Table MD file

**Comment by Ornias1993** [comment]
Awesome, thanks! :)

**Pull request merged**
