### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by CiDi-IT**
This is the modified version of the python file to have full access even with the latest version of BESST

### CODE REVIEW

**Review by Ornias1993 — CHANGES_REQUESTED** [review]
It seems you changed the lineendings which causes the complete file to be replaced.
you also seem to have removed by authList fix for non-6 usertypes.

The only thing new is the different URL, which BESST version requires this new URL?
(which also isn't technically required to be set anyway)

"The modified version"
Yet nothing functional is modified and my modifications are removed.

So it looks more like a revert of my fixes.

**Comment by CiDi-IT** [comment]
With the version of BESST 1.2.26, I had to make these changes, otherwise you don't have access to the settings.

**Comment by Ornias1993** [comment]
It would've been nice if you didn't remove the improvements I made that bypass some security settings for other usertype than usertype 6.

**Comment by Ornias1993** [comment]
Shoot my PC is tripping it... sorry for the random close.

**Comment by Ornias1993** [comment]
> With the version of BESST 1.2.26, I had to make these changes, otherwise you don't have access to the settings.

Could you explain which change you refer to?

It looks you're quite new to GIT...
- With a PR, it's normal to explain in the title what you are changing with a few words (so not 'add files via upload')
- It's also important to describe in the description in more detail what the changes are and why these changes are required

**Comment by Ornias1993** [comment]
With changes I think you mean ```'status':1``` to ```'status':6```?

**Comment by CiDi-IT** [comment]
Sorry, I actually don't know Github that well.  I have not modified your file, but I uploaded a new one that I had modified in February, maybe I was wrong to give it the same name.

I know the Bafang M600 quite well, I'm the one who invented the system via the Can innomaker interface

**Comment by Ornias1993** [comment]
> Sorry, I actually don't know Github that well. I have not modified your file, but I uploaded a new one that I had modified in February, maybe I was wrong to give it the same name.
> 
> I know the Bafang M600 quite well, I'm the one who invented the system via the Can innomaker interface

Did you test our version at all, or did you just asume you should replace what we've done with your version from february?

It's assumed kinda rude to revert improvements other people have made with work from months ago, unless a bug got introduced with the improvements...

**Comment by Ornias1993** [comment]
Closing, because this PR has severe form errors and it's not clear what this user wants to accomplice with the PR.

**Comment by CiDi-IT** [comment]
Sorry, I'm not familiar with github procedures, I'll remember it for next time.  I have tested the file and it does not let me access the BESST program in constructor mode, tomorrow I will do further tests.

**Comment by Ornias1993** [comment]
I'm going to merge this just to be sure, as it cannot hurt either! :)

**Pull request merged**
